[package]
name = "wayland-remote-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
calloop = { workspace = true, features = ["signals"] }
image.workspace = true
libc.workspace = true
quinn.workspace = true
rcgen.workspace = true
rustls.workspace = true
sha2.workspace = true
smithay = { workspace = true, features = ["renderer_gl", "backend_gbm"] }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
wayland-remote-protocol.workspace = true
wayland-server.workspace = true

[dev-dependencies]
tempfile.workspace = true
wayland-client.workspace = true
wayland-protocols = { workspace = true, features = ["client"] }
wayland-remote-viewer = { path = "../viewer" }

[[bin]]
name = "wayland-remote-server"
path = "src/main.rs"

[[bin]]
name = "wr-dump"
path = "src/bin/wr-dump.rs"

[lints]
workspace = true
